---
#Från uppgift 5 och 6: Installerar och startar webservern nginx-
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

#Skapar Conf.d katalog där mina virtuella host filer ska ligga.
- name: Ensure /etc/nginx/conf.d directory exists
  ansible.builtin.file:
    path: /etc/nginx/conf.d
    state: directory
    owner: root
    group: root
    mode: '0755'

#Skapar web root katalog och index.html fil.
- name: Ensure web root directory exists
  ansible.builtin.file:
    path: /var/www/example.internal/html/
    state: directory
    owner: root
    group: root
    mode: '0755'

#Lägger ut startsidan index.html.
- name: Deploy index.html
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/example.internal/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

#Uppgift: 10 vhost-konfigurattion från template.
- name: Ensure the nginx configuration is updated for example.internal
  ansible.builtin.template:
    src: example.internal.conf.j2
    dest: /etc/nginx/conf.d/example.internal.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx

#HTTPS-konfiguration, separat fil.
- name: Copy HTTPS config file (disabled so it does not override real vhost)
  ansible.builtin.copy:
    src: https.conf
    dest: /etc/nginx/conf.d/https.conf.disabled
    owner: root
    group: root
    mode: '0644'

#Startar och aktiverar nginx — körs EFTER att alla config-filer är på plats.
- name: Ensure nginx is enabled
  ansible.builtin.service:
    name: nginx
    enabled: true

#Uppgift 11: Skapar användare med loop från en lista.
- name: Create users with loop
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups | join(',') }}"
    append: false
  loop: "{{ users }}"
